version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "consumer-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18i3wsmtd8www"
s3_prefix = "consumer-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
